### ISSUE TITLE
Backend app page is not displaying - Issue with SSL cert

### ISSUE THREAD

**Issue by amarnathi** [apioo/fusio-docker#10]
I have tried doing git clone of this repo and tried using `docker-compose up -d` to bring up the docker container. The app Fusio is not getting created

The problem when the fusio container is brought up and executing the fusio marketplace installation, it is giving the cert error. I have tried updating docker-compose.yml with php bin/fusio marketplace:install **-d** fusio to ignore the cert , it works great

root@1d5875ba9dd4:/var/www/html/fusio# php bin/fusio marketplace:install fusio
                                                                                                                                           
  cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by chriskapp** [comment]
Hi, ok maybe there was a short time where our cert was not valid but it should work now. We have added the -d option to ignore SSL verification for users on windows systems etc. where curl has no fitting pem file but inside the docker env we should be able to verify the cert. I will close this issue but please let me know if there are further issues.
