### ISSUE TITLE
fail to login after installation

### ISSUE THREAD

**Issue by BillyTheCowBoy** [apioo/fusio-docker#13]
![image](https://user-images.githubusercontent.com/61674878/136076045-91cb79d0-5ed7-4b24-8adf-934452b3f7be.png)

Error message has shown in Browser:
fusio.min.js:223 POST http://<IP>/apps/authorization/token 404 (Not Found)

Docker command used to start the backend:
docker run -d --name fusio \
  -p 80:80 \
  --link mysql_fusio:db \
  -e "FUSIO_PROJECT_KEY=42eec18ffdbffc9fda6110dcc705d6ce" \
  -e "FUSIO_DOMAIN=XXX" \
  -e "FUSIO_HOST=XXX" \
  -e "FUSIO_URL=http://XXX" \
  -e "FUSIO_URL=http://XXX/apps" \
  -e "FUSIO_ENV=prod" \
  -e "FUSIO_DB_NAME=fusio" \
  -e "FUSIO_DB_USER=fusio" \
  -e "FUSIO_DB_PW=61ad6c605975" \
  -e "FUSIO_DB_HOST=mysql_fusio" \
  -e "FUSIO_BACKEND_USER=demo" \
  -e "FUSIO_BACKEND_EMAIL=demo@fusio-project.org" \
  -e "FUSIO_BACKEND_PW=61ad6c605975" \
  fusio/fusio
  
  Docker command used to start the database:
  docker run -d --name mysql_fusio \
  -e "MYSQL_ROOT_PASSWORD=61ad6c605975" \
  -e "MYSQL_USER=fusio" \
  -e "MYSQL_PASSWORD=61ad6c605975" \
  -e "MYSQL_DATABASE=fusio" \
  mysql:5.7
  
  
  Do you have any idea? Thanks

**Comment by arejae** [comment]
i have same problem, what i do is change this part => -e "FUSIO_APPS_URL=http://XXX/apps" 
drop the container and create again.

**Comment by BillyTheCowBoy** [comment]
Thank you . it works after changed  e "FUSIO_URL=http://XXX/apps"   to -e "FUSIO_APPS_URL=http://XXX/apps"
