### ISSUE TITLE
Enable Oci8

### ISSUE THREAD

**Issue by halloigi** [apioo/fusio-docker#17]
how enable oci8 in dockerfile?i've tried with instantclient, but no luck

RUN apt-get -y install libaio1 libc6-dev
COPY basic.zip /tmp/
COPY sdk.zip /tmp/
RUN unzip /tmp/basic.zip -d /usr/local/
RUN unzip /tmp/sdk.zip -d /usr/local/
RUN mv /usr/local/instantclient_21_6 /usr/local/instantclient

RUN sh -c "echo /usr/local/instantclient > /etc/ld.so.conf.d/oracle-instantclient.conf"
RUN ldconfig

RUN export LD_LIBRARY_PATH=/usr/local/instantclient:$LD_LIBRARY_PATH
RUN export PATH=/usr/local/instantclient:$PATH

RUN docker-php-ext-configure pdo_oci --with-pdo-oci=instantclient,/usr/local/instantclient

RUN pecl channel-update pecl.php.net

RUN pecl install pecl install oci8 && memcache-8.0 \
    && pecl install mongodb-1.12.0

RUN docker-php-ext-enable \
    memcache \
    mongodb

RUN docker-php-ext-enable pdo_oci oci8

thanks

**Comment by chriskapp** [comment]
Hi, you can checkout this PR s. https://github.com/apioo/fusio-docker/pull/16 where a user has enabled oci8 for the container

**Comment by chriskapp** [comment]
Hey, we have just added also an oracle flavor to our base image which can be used if you need oracle support.
