### ISSUE TITLE
SSL https port 443

### ISSUE THREAD

**Issue by pedroponte** [apioo/fusio-docker#18]
Hi there,

any chances of enabling port 443 for security reasons?

Getting an error due to this, I'm running a reverse proxy (nginx proxy manager in front of fusio https -> http)

TIA

![Screenshot 2022-11-21 at 22 50 33](https://user-images.githubusercontent.com/5510270/203173999-abe5e193-46e7-4e8c-8926-271cd74f23d8.png)

**Comment by chriskapp** [comment]
Hey, you probably only need to set the fitting FUSIO_URL using https then it should work.
