### ISSUE TITLE
Marketplace is not in docker image

### ISSUE THREAD

**Issue by ChPro97** [apioo/fusio-docker#19]
Hello friend, I'm trying to use Fusio and I'm having problems. The marketplace is not opening on the backend, I think I'm having problems with the proxy. I tried to carry out the process of making a build from the fusio/fusio image and installing Swagger and PMA in the Dockerfile file. Both installed, but PMA refuses access (I'm using the same credentials as in this git) and Swagger gives the error "Fetch error Not Found ${API_URL}system/export/openapi/*/*"

**Comment by chriskapp** [comment]
Hi @ChPro97 regarding Swagger this looks like the url "${API_URL}" was not replaced, normally this should be replaced on installation with the configured API url, but you can also manually replace this, by editing the index.html file or you can also use the marketplace:env command.
