### ISSUE TITLE
Updating fusio to 0.9.5 on Dockerfile breaks image building

### ISSUE THREAD

**Issue by dnng** [apioo/fusio-docker#2]
# Description

I need to customize the Dockerfile to install apache specific modules and other custom configs, so I tried rebuilding the image, but when composer tries to install an adapter, it fails because of versioning issues.

# Steps to reproduce

1. Update `Dockerfile` to point to latest fusio release:
```
ENV FUSIO_VERSION "0.9.5"
ENV FUSIO_SHA1 "7dea63785fe1f1f6cf92963b92f7b95baf45fcf2"
```

2. Change `docker-compose.yml` to point to new image name (in my case, `my_image/fusio:latest`) 
3. Run `docker build`
```
docker build -t my_image/fusio:latest .
```
# Expected behavior
The build process generates a new image with proper tag

# Observed Behavior
The build process throws an error when compose tries to install the adapters:
```
Step 37/64 : RUN cd /var/www/html/fusio && /usr/bin/composer require fusio/adapter-amqp
 ---> Running in 212cd76f2bb9
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^1.0 for fusio/adapter-amqp
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: fusio/engine[v1.0.0, v0.7.8].
    - Can only install one of: fusio/engine[v1.0.0, v0.7.8].
    - Can only install one of: fusio/engine[v1.0.0, v0.7.8].
    - fusio/adapter-amqp v1.0.0 requires fusio/engine ^1.0 -> satisfiable by fusio/engine[v1.0.0].
    - Installation request for fusio/adapter-amqp ^1.0 -> satisfiable by fusio/adapter-amqp[v1.0.0].
    - Installation request for fusio/engine (locked at v0.7.8) -> satisfiable by fusio/engine[v0.7.8].


Installation failed, reverting ./composer.json to its original content.
The command '/bin/sh -c cd /var/www/html/fusio && /usr/bin/composer require fusio/adapter-amqp' returned a non-zero code: 2
```

How should I proceed? I'm having trouble finding the proper dependency adapter versions for a given fusio release.

**Comment by k42b3** [comment]
Hi, thanks for the info. So last weekend we have raised the version of most connectors to 1.0 in preperation for the Fusio 1.0 release. The problem is now that we install additional connectors in the `Dockerfile`:

```
# install additional connectors
RUN cd /var/www/html/fusio && /usr/bin/composer require fusio/adapter-amqp
RUN cd /var/www/html/fusio && /usr/bin/composer require fusio/adapter-beanstalk
...
```

Composer now tries to install these 1.0 versions which require a different engine package then the old release. So to solve this problem you could remove these additional connectors or you could wait until we update the docker image which is on top of our todo list.

**Comment by dnng** [comment]
What I did to make it work was to go to [packagist](https://packagist.org) and check every single connector version and set connector versions on the `Dockerfile` to the ones prior to v1.0.0:

```
RUN cd /var/www/html/fusio && /usr/bin/composer require fusio/adapter-amqp:v0.4.0
RUN cd /var/www/html/fusio && /usr/bin/composer require fusio/adapter-beanstalk:v0.4.0
RUN cd /var/www/html/fusio && /usr/bin/composer require fusio/adapter-elasticsearch:v0.2.0
RUN cd /var/www/html/fusio && /usr/bin/composer require fusio/adapter-memcache:v0.4.0
RUN cd /var/www/html/fusio && /usr/bin/composer require fusio/adapter-mongodb:v0.4.0
RUN cd /var/www/html/fusio && /usr/bin/composer require fusio/adapter-redis:v0.2.0
RUN cd /var/www/html/fusio && /usr/bin/composer require fusio/adapter-soap:v0.4.0
```
So if anyone needs to make it work asap, this should work :-)

**Comment by k42b3** [comment]
So we have just updated the docker image to the latest 0.9.6 version
https://hub.docker.com/r/fusio/fusio/
