### ISSUE TITLE
Issue login in @ backend after instalation in docker with docker-compose

### ISSUE THREAD

**Issue by fresnedajuan** [apioo/fusio-docker#21]
Is there any guideline on how to configure this properly? as far as I read is related to the url that is configured on the ENV. But I cant seem to make it work under docker.

Gives "could not authenticate"

**Comment by chriskapp** [comment]
Hi @fresnedajuan I would assume that your FUSIO_URL is not correctly configured, but could you show me the response of the login request in the developer console?
