### ISSUE TITLE
cannot login to fusio backend with admin user

### ISSUE THREAD

**Issue by miconx** [apioo/fusio-docker#3]
after starting the containers with docker-compose i cannot login to the backend app 
i get an angular js error in the browser console 
see screenshot ....
<img width="1420" alt="bildschirmfoto 2018-02-07 um 09 52 46" src="https://user-images.githubusercontent.com/504850/35907018-ee996cd8-0bec-11e8-91ce-6a5cdab3d10d.png">

**Comment by k42b3** [comment]
Hi, sorry for the late reply, but could you checkout the latest docker image which I have just published. This may have already solved the issue.

**Comment by miconx** [comment]
with the last checkout i cannot even start with  docker-composer - see error:
root@webdev01:/opt/fusio# docker-compose up -d
Creating fusio_mysql_fusio_1

ERROR: for mysql_fusio  Cannot start service mysql_fusio: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"fork/exec /usr/bin/dockerd (deleted): no such file or directory\\\"\"\n"
ERROR: Encountered errors while bringing up the project.

**Comment by k42b3** [comment]
Mhh this looks like the database container `mysql_fusio` has a problem. Could you maybe delete any existing database folder in the repo and try it again. I just created a container with the latest image using `docker-compose up -d` without a problem, we have also a travis test to check the image at: https://travis-ci.org/apioo/fusio-docker

**Comment by jpgollnitz** [comment]
I've also experienced this issue with the latest docker image. I have tried deleting the entire fusio-docker directory and cloning the image. The front end does not accept my login credentials, even verified again in the docker-composer.yml file.

**Comment by chriskapp** [comment]
Could you post the output of the docker image. The image writes the apache logs to stdout so you should see every incoming request if you start it with `docker-compose up`. If you use the credentials from the docker compose yaml `FUSIO_BACKEND_USER` and `FUSIO_BACKEND_PW` you should be able to login.

**Comment by jpgollnitz** [comment]
I'm seeing a lot of errors and warnings that all basically say: 
PHP Fatal error: require_once(/var/www/html/fusio/public/../vendor/autoload.php failed to open stream: no such file or directory in /var/www/html/fusio/public/index/php on line 22.

**Comment by jpgollnitz** [comment]
![image](https://user-images.githubusercontent.com/16770825/51061415-38f59200-15c1-11e9-852c-d1d951ed3fe7.png)

![image](https://user-images.githubusercontent.com/16770825/51061444-56c2f700-15c1-11e9-9f5d-357ad9a0e615.png)

**Comment by jpgollnitz** [comment]
My previous attempts to re-download and install the docker image were unsuccessful. 

Then, I went onto the server, did apt-get remove apache2 and apt-get remove mysql and apt-get remove php and let docker-composer handle all of the dependencies.

Alas, I was able to successfully log into the backend.

**Comment by chriskapp** [comment]
I will close this issue since it looks like all problems are solved, if there are still any issues please open a new issue.
