### ISSUE TITLE
Error when trying to go to backend

### ISSUE THREAD

**Issue by redndahead** [apioo/fusio-docker#5]
I can go to 127.0.0.1 and see that it says the installation was successful. When I go to 127.0.0.1/fusio I get the error:

{
    "success": false,
    "title": "Internal Server Error",
    "message": "Unknown location"
}

Any ideas on what could be going on?

**Comment by redndahead** [comment]
It seems if I go to 127.0.0.1/fusio/index.htm it works. I wonder if apache is not configured to look at index.htm files.

**Comment by RightInTwo** [comment]
for me it is /fusio/public/fusio/ in the test setup (which of course should be fronted with a nginx for production)

**Comment by chriskapp** [comment]
Hi, yes this true, I think we should rename the `index.htm` to `index.html` which is then also inline with all other apps. I will update this for the next release.

**Comment by samarthya** [comment]
/fusio/index.html worked for me. I was wondering how to get it working.

**Comment by chriskapp** [comment]
Yes so in the latest released we have renamed the backend app file to `index.html` so I think we can close this issue.
